pearcej/comp-sys-sec

source/ch1-introduction.ptx
Sub issue for issue https://github.com/pearcej/comp-sys-sec/issues/1 to add descriptions to images for accessibility on Chapter 1.
=> Added descriptions for images for Chapter 1 fixes issue #32

source/ch2-cryptography.ptx
Fixed issue #9  
The code was previously not in a code block, indicating it was code.
I added a program and input tag to make the code block and contain the actual code.
I tested the code through my local host.
=> Fixed putting the code in a code section

source/ch3-malware.ptx
Dr Jan requested something be done about the look of it; it was in a note, but Tristian didn't like how it looked, so I made it a figure.
Closes issue #31 
relates to issue #21 
built and ran locally
=> added figure to 3.2 fixes issue #31

source/ch2-cryptography.ptx
=> fix xml ids in ch2

source/ch2-cryptography.ptx
Fixes issue #34 
I added descriptions to the images through the chapter and any decorative tags necessary. 
Issue #34 
Yes it has been looked at by Austin and has been build/inspected.
=> Added descripion to images that CH2 fixes issue #34

source/ch3-malware.ptx
Fixes issue #48 
I added description tags to all the images and went into detail for images for chapter 3.
it goes back to issue #1 
It has been reviewed by Colin and has been built locally and works through the accessibility inspect
=> Fixing ch3 imagetags issue#48

source/ch4-protocols.ptx
Fixes issue #50 
Adds descriptions to every image in Chapter 4 to help accessibility
Fixes sub-issue of issue #1 
I ran a local build but I have not verified with colleagues yet. It will stay as a draft until verified further.
=> Adds description to all the images in chapter 4 fixes issue #50

source/ch4-protocols.ptx
@pearcej I used the question to format these. It seems to make sense because they all appear to be questions for the reader. I could also use any of the other example like elements found here https://pretextbook.org/doc/guide/html/basics-s-examples.html, but the question tag looked like the best fit. I initially used a note tag, but decided to use the question tag instead.
fixes issue #53 
I built and viewed  it and had austin and elijah check my code
=> 4.5 issue#53

source/ch4-protocols.ptx
I re-wrote the table using the pretext table tags
fixes issue #51 
related to issue #22 
ran built and checked out by tristan
=> 4.3.3 missing table

source/ch2-cryptography.ptx
Fixed issue #2 and #5 
Fixed the title "Case Study: Equifax" in 2.1 by making it a subsection. I also got rid of HTML tags for listing and replaced with with <p> and used <term> to bold the text.
It was tested using my local host.
=> Fixed the heading issue for issue #2 and fixed the listing issue for issue #5

source/ch4-protocols.ptx
I made all em tags terms, and indexed key terms so they show up in the index.
I made all em tags terms, and indexed key terms so they show up in the index.
fixes issue #13
built and tested
reviewed by Elijah @FlashEb
=> Ch4 adding terms

source/ch3-malware.ptx
This PR addresses two related formatting issues in a single branch due to the interdependency of changes. To fix the example rendering problem effectively, I had to first clean up and restructure the document formatting. Doing this in separate branches would have introduced redundant work and potential merge conflicts.
Removed leftover HTML comments from sections 3.1–3.3.
Replaced `<paragraphs>` tags with structured `<section>`, `<subsection>`, and `<subsubsection>` elements.
Reformatted all examples, replacing incorrect `<p> `usage with proper `<example>` tags.
Replaced deprecated or misused tags like `<dl>`,` <dt>`, and `<dd>` with semantic subsections for better clarity and formatting.
Left instances of hardcoded numbering untouched, as they are being handled in other active PRs. In …
=> A lot of work was done in order to update information Fixes issue#46 & #38

source/ch6-security-solutions.ptx
Remove naming duplications in xml:id tags
=> fix xml:ids in ch6

source/ch7-access-controls.ptx
Remove duplications in xml:ids in ch 7
=> remove xml:id duplications ch7

source/ch10-virtualization.ptx
Fixes all xml:id duplications in ch10
=> fix xml:ids in ch10

source/ch9-incident-response.ptx
Fixed duplicated xml:id tags, removed unneeded comments, corrected headers, and replaced paragraphs with subsections
=> improvements to ch 9

source/ch8-vulnerability-management.ptx
Fixes issue #68 
Adds description to images in chapter 8
This fixes a subissue of issue https://github.com/pearcej/comp-sys-sec/issues/1
I ran a local build and saw it working fine and it was signed off on by @coco3427
=> Added image descriptions to chapter 8 fixes issue #68

source/ch8-vulnerability-management.ptx
Correct redundant xml:ids, remove autogenerated comments, improve headers, change paragraphs to subsections.
=> Format fixes in ch8

source/ch1-introduction.ptx
shall fixes to formatting for readability.
=> small format improvments in ch1

source/ch7-access-controls.ptx
Fixes issue #73 
Adds description to images in chapter 7
This fixes a subissue of issue https://github.com/pearcej/comp-sys-sec/issues/1
I ran a local build and saw it working fine and it was signed off on by @coco3427
=> Fixing ch7 imagetags issue#73

source/ch3-malware.ptx
I removed all XML IDs throughout the chapter and left in the numbers because Colin had told me we wanted to keep them for now.
partial fix #43 
Built locally, it looks good.
=> Removed All Duplicate XML Id's from ch3 left num in title issue #43

source/ch10-virtualization.ptx
Adds content missing from chapter 10 and converts paragraphs to subsections
=> add missing content in ch10

source/ch10-virtualization.ptx
fixes several pretext problems in ch10
=> fix PreTeXt problems ch10

source/ch6-security-solutions.ptx
Fixes issue https://github.com/pearcej/comp-sys-sec/issues/78
Adds description to images in chapter 6
This fixes a subissue of issue https://github.com/pearcej/comp-sys-sec/issues/1
I ran a local build and saw it working fine, but still needs peer reviewed.
=> Adds image descriptions to chapter 6 and fixes issue #78

source/ch9-incident-response.ptx
Improved layout in ch9, including placing lab before review questions like in other chapters
=> formatting improvments ch9

source/ch5-attacks.ptx
I went through and fixed all of the formatting errors in CH5 and Added back all of the missing content.
fixes issue #23
I built and tested my changes and had them checked off by tristan.
=> Ch5 missing formating

source/ch2-cryptography.ptx
Partial commit for chapter 2 issue #88 to fix formatting. Fixed chapter 2.11, adding notes and question tags where needed.
Tested on my local host.
=> Fixed Formatting in 2.11 for questions and notes

source/ch3-malware.ptx
Removed the `<dl> <dd> <dt>` tags and changed them to the correct ` <p>` tags. changed <paragraphs> to <subsections>
partial fix #84  
Built locally, it looks good.
=> partial PR, creates terms and subsections for 3.5.1-3.5.3 partial fix issue#84

source/ch2-cryptography.ptx
=> Remove autogenerated comments

source/ch3-malware.ptx
fix paragraphs and exercises in ch3
=> fix formatting in ch3

source/ch1-introduction.ptx, source/ch3-malware.ptx, source/ch8-vulnerability-management.ptx, source/ch9-incident-response.ptx
=> fix-escallation

source/ch3-malware.ptx, source/ch4-protocols.ptx, source/ch7-access-controls.ptx
add introduction tags where needed, remove auto-added comments, add missing content
=> Fix pretext

source/ch5-attacks.ptx
Fixes issue #100 
Adds many descriptions and short descriptions for images.
This fixes a subissue of issue https://github.com/pearcej/comp-sys-sec/issues/1
I ran a local build and saw it working fine and it was signed off on by @Austing767
=> Added image descriptions to all the images fixes issue #100

source/ch4-protocols.ptx
fixes footnote in ch4 and adds protocol as a term and to the index
=> fix footnote in ch4

source/ch6-security-solutions.ptx
Removes a single caption from chapter 6
Removes a single caption from chapter 6 and uses the short descriptions/description to be more uniform
Fixes issue #116 
I ran the build locally and inspected from the browser.
=> Removed the excess caption from Chapter 6 fixes issue #116

source/ch4-protocols.ptx
I removed captions from images
I removed captions from images to help make the book's accessibility much more uniform
This fixes issue #114 
I ran a local build and inspected it through the browser.
=> Removed captions from chapter 4 fixes issue #114

source/ch8-vulnerability-management.ptx
Removes captions from chapter 8
Removes caption from chapter 8 and uses the short descriptions/description to be more uniform
Fixes issue #118 
I ran the build locally and inspected from the browser.
=> Removed captions for some images fixes issue #118

source/ch9-incident-response.ptx
Removes one caption
Removes a single caption from chapter 9 and uses the short descriptions/description to be more uniform
Fixes issue #120 
I ran the build locally and inspected from the browser.
=> Removed a caption fixes issue #120

source/ch10-virtualization.ptx
Removes a single caption from chapter 10
Removes a single caption from chapter 10 and uses the short descriptions/description to be more uniform
Fixes issue #122 
I ran the build locally and inspected from the browser.
=> Removes one caption from image fixes issue #122

source/ch5-attacks.ptx
I added the missing note to the pre-text version. This was the only missing content in chapter 5.
Fixes issue #23 
built and ran locally.
reviewed by @Tristan-Raz
=> Added missing note to 5.7 fixes issue #23

source/ch3-malware.ptx
- This pull request fixes several issues to add keywords and indices in Chapters 1-3.3.
- I added term and idx tags to words that I believe needed them.
- I test the changes on my local host.
- This fixes issues #4 #7 #10 #11 .
=> Fixing issue 4, 7, 10, 11

source/ch10-virtualization.ptx, source/ch7-access-controls.ptx, source/ch9-incident-response.ptx
=> replace footnotes

source/ch5-attacks.ptx
closes #113 
addresses #3 for ch5
=> improve ch5 styling

source/ch2-cryptography.ptx
Went through the file and every instance of <title>, I looked to see if there were hardcoded numbers and removed them.
Partial fix issue #3
Built and viewed locally, looks great!
=> Removed hardcoded chapter numbers partial fix issue #3

source/ch4-protocols.ptx
Removed hard-coded chapter numbers, globally replaced paragraphs with sections
Partial fix issue #3 
Built and viewed locally, looks great!
=> Removed HardCoded numbers, global replace paragraphs with subsection partial fix issue #3

source/ch9-incident-response.ptx
partially addresses #3 for chaoter 9
=> improve ch9 styling

source/ch8-vulnerability-management.ptx
partially addresses #3 for ch8
=> removes hard-coding of sections in ch8

source/ch7-access-controls.ptx
Removed the duplicate title numbers for ch7.
Partial fix issue #3 
Built and ran locally looks good.
=> Removed the title numbers for ch7 partial fixes issue #3

source/ch6-security-solutions.ptx
added all keywords and index tags to chapter 6 and removed all section numbers.
fixes issue #15
partial fix fir issue #3 
built and ran
checked by austin
=> Ch6 keywords

source/ch9-incident-response.ptx
added terms to ch 9 and indices. also fixed section number.
fixes issue #18 
built and viewed.
=> fixes issue #18

source/backmatter.ptx, source/frontmatter.ptx
Imrove frontmatter and backmatter
=> improve auxilliary materials

source/ch2-cryptography.ptx, source/ch4-protocols.ptx
partially addresses issue #101.
Partially addresses issue #146 .
=> Add codespaces to ch2 and ch4

source/ch1-introduction.ptx, source/ch2-cryptography.ptx, source/ch3-malware.ptx
partially addresses #158  for chapters 1, 2, and 3.
=> add captions to ch1 - ch3

source/ch2-cryptography.ptx, source/ch4-protocols.ptx, source/ch5-attacks.ptx
partially addresses #158 for chapters 4 and 5
partially addresses #80 for chapter 5
=> Improvements to chapters 4 and 5

source/ch4-protocols.ptx
closes #166 and partially addresses #167 for ch4 lab on nmap.
=> Nmap improvement

source/ch4-protocols.ptx, source/ch8-vulnerability-management.ptx
=> Improve ch4 ch8

source/ap-bash-cheatsheet.ptx, source/ch6-security-solutions.ptx, source/ch7-access-controls.ptx
makes progress on #165 
makes progress on #167
=> improve ch6 and ch7 labs

source/ch7-access-controls.ptx
I added some commands to the Linux to work, and I also added some interactions 
Added sudo to commands so that they work with codespace and Dockerfile, as the password is not mentioned. Also added a brief hint for the harder question. Fixes issue #191
Fixes issue #191 
Built and reviewed by @coco3427
=> Fixed some Linux commands and added interactions

source/ch4-protocols.ptx
I added an interactive element that asks the user what the hidden password is.
issue #196
I have built and tested it.
=> fixing issue #196.

source/ch3-malware.ptx
I added an MC question, created a list of the questions previously for readability, broke up paragraphs, rewrote them for clarity, instructions on what to do without giving away how to complete the lab, and added a hint to help.  
I converted one of the free-response questions into a multiple-choice question to make it interactive. During our time in Taiwan, this lab was one of the more confusing ones, so I added more precise instructions, broke up some of the longer paragraphs, and rewrote the original “instructions” to be more understandable, while still preserving the learning experience and not giving away the solution. I also added an interactive hint to help guide the reader.
I initially tried using free-response/short-answer questions, but the prompt wouldn’t display correctly. …
=> Chapter 3 interactivity & Instructions

source/ch4-protocols.ptx
Adds the last interactive needed for security book in Chapter 4 and fixes issue #187
This is the last interactive needed for the security book to help the user, it now fixes the major issue #187 
Fixes issue #187 
It has been built locally and reviewed by @FlashEb
=> Adds the last interactive needed for security book fixes issue #187
